[default.logging]
version = 1

[default.logging.loggers.service]
handlers = ["service"]
level = "DEBUG"

[default.logging.handlers.service]
class = "logging.handlers.RotatingFileHandler"
filename = "/var/log/kreoshine/kreo_products/service.log"
maxBytes = 10485760
backupCount = 4
formatter = "basic"
level = "DEBUG"

[development.logging.formatters.basic]
format = "%(asctime)s %(levelname)-8s [%(filename)s:%(lineno)s] %(message)s"

[production.logging.formatters.basic]
format = "%(asctime)s %(levelname)-8s %(message)s"

[production.logging.handlers.service]
level = "INFO"
