services:
  postgres:
    container_name: postgres
    image: postgres:latest
    command: postgres
    environment:
      PGDATA: "/var/lib/postgresql/data/"  # default /var/lib/postgresql/data/
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
